---
dhcp_ctrl_agent_config:
  Control-agent:
    trust-anchor: /path/to/the/ca-cert.pem
    cert-file: /path/to/the/agent-cert.pem
    key-file: /path/to/the/agent-key.pem
    cert-required: true
    authentication:
      type: basic
      realm: kea-control-agent
      clients:
        - user: admin
          password: "1234"
    control-sockets:
      dhcp4:
        comment: main server
        socket-type: unix
        socket-name: /path/to/the/unix/socket-v4
      d2:
        socket-type: unix
        socket-name: /path/to/the/unix/socket-d2
    loggers:
      - name: kea-ctrl-agent
        severity: INFO
