kea_ddns_config:
  DhcpDdns:
    ip-address: 10.42.0.1
    dns-server-timeout: 100
    ncr-protocol: UDP
    ncr-format: JSON
    port: 53001
    tsig-keys: []
    forward-ddns:
      ddns-domains: []
    reverse-ddns:
      ddns-domains: []
