[project]
authors = [
  {name = "Asher Norland", email = "asher.norland@gmail.com"},
] 
dependencies = [
  "ansible-dev-tools>=25.5.2",
  "ansible-vault>=4.1.0",
  "pydantic>=2.11.7",
  "pyyaml>=6.0.2",
  "docker>=7.1.0",
] 
description = "Synodic monorepo for Ansible roles" 
license = {text = "MIT"} 
name = "ansible" 
readme = "README.md" 
requires-python = ">=3.12" # Pinned to Ubuntu 24 version
version = "0.1.0" 

[dependency-groups]
lint = [
  "ruff>=0.12.0",
  "mypy>=1.16.1",
  "types-docker>=7.1.0.20250523",
]
test = [
  "dnspython>=2.7.0",
  "molecule>=25.6.0",
  "pytest>=8.4.1",
  "pytest-mock>=3.14.1",
  "molecule-plugins[docker]>=23.7.0",
]

[tool.pytest.ini_options]
log_cli = true
addopts = "-v"
testpaths = [
  "tests",
]

[tool.mypy]
exclude = "__pypackages__"
plugins = ["pydantic.mypy"]
strict = true

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = [
  "D206",
  "D300",
  "D415",
  "E111",
  "E114",
  "E117",
]
select = [
  "D", # pydocstyle
  "F", # Pyflakes
  "I", # isort
  "PL", # pylint
  "UP", # pyupgrade
  "E", # pycodestyle
  "B", # flake8-bugbear
  "SIM", # flake8-simplify
  "PT", # flake8-pytest-style
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pdm.options]
update = ["--update-all"]

[tool.pdm.version]
source = "scm"

[tool.pdm.scripts]
analyze = "ruff check tests"
ansible-lint = "ansible-lint"
format = "ruff format"
lint = {composite = ["analyze", "format", "type-check", "ansible-lint"]}
test = "pytest tests"
test-integration = "pytest tests/integration"
test-unit = "pytest tests/unit"
type-check = "mypy ."

[tool.pdm]
distribution = false # We publish this to Galaxy, not PyPI
