[project]
authors = [
  {name = "Asher Norland", email = "asher.norland@gmail.com"},
] 
dependencies = [
  "ansible", # Full ansible for vscode extension
  "ansible-vault",
  "pydantic",
  "pyyaml",
] 
description = "Synodic monorepo for Ansible roles" 
license = {text = "MIT"} 
name = "ansible" 
readme = "README.md" 
requires-python = ">=3.12" # Pinned to Ubuntu 24 version
version = "0.1.0" 

[dependency-groups]
lint = [
  "ansible-lint",
  "ruff",
  "mypy",
]
test = [
  "dnspython",
  "molecule",
  "pytest",
  "pytest-mock",
  "pytest-ansible",
  "molecule-plugins[docker]",
]

[tool.pytest.ini_options]
log_cli = true
markers = [
  "setup: Tests that should be run prior to any automation, verifying static IP setup",
]
testpaths = [
  "tests",
]

[tool.mypy]
exclude = "__pypackages__"
plugins = ["pydantic.mypy"]
strict = true

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = [
  "D206",
  "D300",
  "D415",
  "E111",
  "E114",
  "E117",
]
select = [
  "D", # pydocstyle
  "F", # Pyflakes
  "I", # isort
  "PL", # pylint
  "UP", # pyupgrade
  "E", # pycodestyle
  "B", # flake8-bugbear
  "SIM", # flake8-simplify
  "PT", # flake8-pytest-style
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pdm.options]
update = ["--update-all"]

[tool.pdm.version]
source = "scm"

[tool.pdm.scripts]
analyze = {cmd = "ruff check tests"}
ansible-lint = {cmd = "ansible-lint"}
format = {cmd = "ruff format"}
lint = {composite = ["analyze", "format", "type-check", "ansible-lint"]}
test = {composite = ["test-pytest"]}
test-molecule = {cmd = "molecule test --all"}
test-pytest = {cmd = "pytest --verbose tests"}
type-check = {cmd = "mypy ."}

[tool.pdm]
distribution = false # We publish this to Galaxy, not PyPI
