- name: Install Kea packages
  ansible.builtin.package:
    pkg:
      - kea
    update_cache: true
    state: present

- name: Configure DHCP server
  ansible.builtin.template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    validate: kea-dhcp4 -t %s
    owner: _kea
    group: _kea
    mode: "0640"

- name: Configure DDNS server
  ansible.builtin.template:
    src: kea-dhcp-ddns.conf.j2
    dest: /etc/kea/kea-dhcp-ddns.conf
    validate: kea-dhcp-ddns -t %s
    owner: _kea
    group: _kea
    mode: "0640"

- name: Enable and start the DHCP service
  ansible.builtin.service:
    name: kea-dhcp4-server
    enabled: true
    state: started

- name: Enable and start the DDNS service
  ansible.builtin.service:
    name: kea-dhcp-ddns-server
    enabled: true
    state: started
