---
driver:
  name: docker
platforms:
  - name: dhcp_server
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    docker_networks:
      - name: kea-net
        driver: bridge
        ipam_config:
          - subnet: 10.42.0.0/24
    networks:
      - name: kea-net
    capabilities:
      - NET_ADMIN
    cgroupns_mode: host

  - name: dhcp_client
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - name: kea-net
    capabilities:
      - NET_ADMIN
    cgroupns_mode: host

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_result_format: json

verifier:
  name: ansible
