---
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: /sbin/init
    capabilities:
      - NET_ADMIN
    cgroupns_mode: host

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml

verifier:
  name: ansible