name: Ansible Lint
on: 
  pull_request:
    branches:
      - development
      - stable
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Ansible Lint
        uses: ansible/ansible-lint@main